channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.1
  - gmpy2==2.1.2
  - numpy==1.26.0
  - packaging==23.2
  - pandas==2.1.1
  - pyyaml==6.0.1
  - torch==2.1.0
  - tqdm==4.66.1
- conda:
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1 -c pytorch -c nvidia
name: MaUn