#!/bin/bash


# echo "ResNet CIFAR10"
# echo "1st seed"
# ./run_max_entropy_ablation.sh  1 "cifar10" "resnet"
# echo "2nd seed"
# ./run_max_entropy_ablation.sh  2 "cifar10" "resnet"
# echo "3rd seed"
# ./run_max_entropy_ablation.sh  3 "cifar10" "resnet"
# echo "4th seed"
# ./run_max_entropy_ablation.sh  4 "cifar10" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "cifar10" "resnet"
###
echo "ResNet CIFAR100"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "cifar100" "resnet"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "cifar100" "resnet"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "cifar100" "resnet"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "cifar100" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "cifar100" "resnet"
###
echo "ResNet MUFAC"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "mufac" "resnet"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "mufac" "resnet"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "mufac" "resnet"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "mufac" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "mufac" "resnet"
###
echo "ResNet MUCAC"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "mucac" "resnet"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "mucac" "resnet"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "mucac" "resnet"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "mucac" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "mucac" "resnet"
###
echo "ResNet PM"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "pm" "resnet"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "pm" "resnet"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "pm" "resnet"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "pm" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "pm" "resnet"
###
echo "ViT CIFAR10"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "cifar10" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "cifar10" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "cifar10" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "cifar10" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "cifar10" "vit"
###
echo "ViT CIFAR100"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "cifar100" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "cifar100" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "cifar100" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "cifar100" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "cifar100" "vit"
###
echo "ViT MUFAC"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "mufac" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "mufac" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "mufac" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "mufac" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "mufac" "vit"
###
echo "ViT MUCAC"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "mucac" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "mucac" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "mucac" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "mucac" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "mucac" "vit"
###
echo "ViT PM"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "pm" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "pm" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "pm" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "pm" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "pm" "vit"
###
echo "ResNet Rocket"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "rocket" "resnet"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "rocket" "resnet"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "rocket" "resnet"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "rocket" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "rocket" "resnet"
##
echo "ViT Rocket"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "rocket" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "rocket" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "rocket" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "rocket" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "rocket" "vit"
###
echo "ResNet Beaver"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "beaver" "resnet"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "beaver" "resnet"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "beaver" "resnet"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "beaver" "resnet"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "beaver" "resnet"
###
echo "ViT Beaver"
echo "1st seed"
./run_max_entropy_ablation.sh  1 "beaver" "vit"
echo "2nd seed"
./run_max_entropy_ablation.sh  2 "beaver" "vit"
echo "3rd seed"
./run_max_entropy_ablation.sh  3 "beaver" "vit"
echo "4th seed"
./run_max_entropy_ablation.sh  4 "beaver" "vit"
echo "5th seed"
./run_max_entropy_ablation.sh  5 "beaver" "vit"